### ISSUE TITLE
Minimizing into system tray not working

### ISSUE THREAD

**Issue by ferenczy** [Yubico/yubioath-desktop#125]
I have been using the version 3.0.1 which used to *close into the system tray* (it means closing application didn't actually terminate it, but instead it minimized it into the system tray), so it had an icon in the system tray and it was still running on the background.

After the upgrade to the **version 4** it looks like the feature is **gone** - no system tray icon, closing the application actually terminates it.

Is it a bug or is it intentional? It was a good feature since it takes some time to execute the application, wait until it reads the credentials, etc.

System: Windows 7 64bit
Yubico Authenticator version: 4.0.0

**Comment by drohm** [comment]
I notieced the same thing.  I would really like "minimize to systray" brought back.

**Comment by dagheyman** [comment]
It was dropped (or rather not re-implemented) on purpose. If the demand is high enough we might want to bring it back though. Could you explain why the systray is better compared to just minimising the window (which pauses reading from the yubikey right now) ?

**Comment by tycho** [comment]
I'd request this be reconsidered. I leave the Yubico Authenticator open all the time, but minimized to the tray because I don't want it taking up valuable space on the taskbar.

**Comment by drohm** [comment]
I want it back for the exact same reason as @tycho. I leave it open all the time and don't want it taking up room on my taskbar.

**Comment by dagheyman** [comment]
Ok, this is maybe a bigger concern on environments where minimised items take up a lot of width, such as on Windows 7 and KDE, compared to macOS and Windows 10? 

Anyway, since three people have complained so far and the release has only been out one day, it should be re-added. Maybe [this component](http://doc-snapshots.qt.io/qt5-5.8/qml-qt-labs-platform-systemtrayicon.html) can be used for this functionality.

**Comment by ferenczy** [comment]
Yes, one of the reasons is to not add more mess on the task bar. I'm using a keyboard shortcut to bring it to the front, not trying to find it on the task bar. I would achieve similar result by closing the application every time, but then it takes some time to read the credentials from the key.

Thank you for considering the re-implementation!

**Comment by dagheyman** [comment]
A new version of the system tray functionality is now implemented on the master branch.

**Comment by ferenczy** [comment]
Thank you for implementing it so quickly! When do you plan to release a new build with this feature, please?

**Comment by dagheyman** [comment]
> Thank you for implementing it so quickly! When do you plan to release a new build with this feature, please?

No real ETA set, but I hope to be able to do a 4.0.2 release in the near future at least.

**Comment by tycho** [comment]
@dagheyman Uh, does this issue need to be reopened? I've built the current git version (4.0.1-16-ge0e59dd) and the "Show in system tray" setting does nothing. Tried restarting the app, and still no tray icon (though the setting value was preserved).

**Comment by dagheyman** [comment]
@tycho I guess you found the tray icon in some way (since you opened #150) ? Any idea what the problem was?

**Comment by tycho** [comment]
@dagheyman Yeah, so it's a really dumb problem. There are two ways that tray icons can be registered in modern Linux distributions, and KDE treats the two paths differently. The old way is xembed. The new way is to use "Status Notifier Items".

Icons registered in the "new" way (e.g. in my case that's just firewall-applet and yubioath-desktop) get shuffled off into the "status and notifications" drawer on the KDE taskbar, where you can't see them unless you expand the drawer. Ones registered in the "old" way (e.g. Dropbox, Pidgin, and damn near every app in existence) show up on the taskbar by default, and in fact cannot appear in the drawer.

In order to get the yubioath-desktop icon to appear on the taskbar instead of in the drawer, I have to set "visibility: shown" in the system tray preferences for that specific icon. Really obnoxious, and totally counter-intuitive.

Despite how frustrating it is, I cannot argue that Status Notifier Items are the "wrong" way to go, but I can certainly argue that KDE treats them incorrectly. Wonder what other desktop environments do with them.

**Comment by tepsley** [comment]
This feature seems to have been, once again, removed. Now from version 6.
Is the reasoning behind this the same, as it was with version 4?
