### ISSUE TITLE
double-clicking tray icon doesn't raise window

### ISSUE THREAD

**Issue by tycho** [Yubico/yubioath-desktop#150]
The window doesn't appear when the tray icon is double clicked. Instead, I have to right click the icon and click "Show credentials"

**Comment by zypA13510** [comment]
Hi, I have a suggestion here. Now that we can minimize to tray and keep running in the background, why don't we make it auto-hide when the key is unplugged, and auto pop out when the key is plugged in? For me, I think this will be very useful.

**Comment by dagheyman** [comment]
@zypA13510 Hi, thanks for your suggestion. I broke it out to a separate issue.

**Comment by dagheyman** [comment]
This is now fixed on master for Windows and Linux. For macOS, since a context menu is used, [listening on double-click](https://bugreports.qt.io/browse/QTBUG-5770?focusedCommentId=351898&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-351898) is not supported. The fix will be included in the next release.
