### ISSUE TITLE
Ubuntu repository build is outdated

### ISSUE THREAD

**Issue by nukeop** [Yubico/yubioath-desktop#181]
Can the build in the PPA be updated to the latest version?

If not, where can I find build instructions?

**Comment by dagheyman** [comment]
For what Ubuntu version? The ppa builds for xenial, zesty and artful are all 4.1.4.
https://launchpad.net/~yubico/+archive/ubuntu/stable/+packages?field.name_filter=yubioath-desktop&field.status_filter=published&field.series_filter=

**Comment by nukeop** [comment]
Is it possible to also update trusty, wily, and vivid? If not, please close this issue.
Thank you for the help and for maintaining this great tool.

**Comment by nukeop** [comment]
I just noticed it's not possible to compile this on trusty (I'm using Mint 17.3 which is equivalent) because the required version of Qt is not available. Are there any known workarounds?

**Comment by dagheyman** [comment]
The reason we're not providing trusty builds is because of missing dependencies. Besides the Qt packages, [pyotherside](https://packages.ubuntu.com/xenial/qml-module-io-thp-pyotherside) needs to be available. Probably other stuff as well. I'm not aware of any good workarounds, but if you manage to build it on trusty, feel free to post some instructions here for others to use.
