### ISSUE TITLE
unorthodox release structure and numbering

### ISSUE THREAD

**Issue by blshkv** [Yubico/yubioath-desktop#208]
https://www.gnu.org/prep/standards/html_node/Releases.html
https://en.wikipedia.org/wiki/Software_versioning

There are few points I would like to highlight from links above:
 - the tarball should unpack into a subdirectory with the same name as the release. Currently, there are two tarballs, the first one has no top directory at all, the second one has double name (yubioath-desktop-yubioath-desktop-4.2.0) in it.
 - 4.2.0b stands for "beta" which must be *before" 4.2.0, not after it. GNU recommends 2 numbers: major and minor. You already have 3rd one for such bugfixes, please use it.
 - do not induce new dependencies on other software lightly (discussed and rejected in the issue #206)

**Comment by emlun** [comment]
1. Sorry, our bad on the first tarball. I'm assuming the second tarball is the one auto-generated by GitHub; we're not fixing that.
 2. If we're talking [semantic versioning][semver], we're both wrong. `4.2.0b` isn't actually a valid version number in semver. We've been using a `b`, `c`, `d`... suffix lately to indicate releases with different packaging but no change to code, which is why we haven't incremented the patch version. But you're right, we should use the versioning scheme properly.
 3. qt-solutions is not a new depenency, it was added more than 9 months ago.

[semver]: http://semver.org/

**Comment by emlun** [comment]
Release [4.2.0+2][rel] is up, with the unpack directory fixed. There's also an alternative release [4.2.0+deps.2][rel] which is identical except it also includes the dependencies. We'll take a look at options for building against local system libraries instead of the bundled ones, and add that to the build documentation if we come up with something good (the `CONFIG += qtsingleapplication` method in your PR didn't seem to work for me when I tried it).

Thanks for reporting!

[rel]: https://github.com/Yubico/yubioath-desktop/releases/tag/yubioath-desktop-4.2.0

**Comment by emlun** [comment]
Actually, upon further internal discussion we decided to de-publish the `+deps` releases. We'll keep `4.2.0+2` with the fixed unpack directory, though. If you need the dependencies bundled, I'd suggest for now to get them as submodules by cloning the repo instead.

**Comment by blshkv** [comment]
that's still weird numbering (with "-" symbol) . Why don't you just use the last (currently 0 and not used) number for patch releases? The second (2) is for minor and the first (4) one for major releases.

Well, it's you call.

**Comment by emlun** [comment]
It's not weird, it's precisely specified in SemVer what it means.

The patch version number is for code changes that make some improvement to internal functionality that's safe and desirable to upgrade to. Since this release has no changes to code and only to packaging, it's not semantically correct to increase the patch version number.
