### ISSUE TITLE
recently CTRL-C broke, only ENTER copies OTP

### ISSUE THREAD

**Issue by alagopus** [Yubico/yubioath-desktop#222]
- Yubico Authenticator version: 4.3.1
- Operating system and version: elementary OS Loki, 4.4.0-104-generic #127-Ubuntu
- YubiKey model and version: Both neo and YK 4
- Bug description summary: Despite the context menu claiming CTRL-C, copy is at ENTER

Attach key, open Yubico Authenticator. Select an Entry, and press CTRL-C. Try pasting: nothing.

Expected result: Current OTP copied to clipboard.

Actual results: No change in clipboard contents.

**Comment by emlun** [comment]
Thanks for reporting! The cause of this is that focus now starts on the search field, so <kbd>Ctrl</kbd>+<kbd>C</kbd> copies from the search field instead of from the selected credential unless you press <kbd>Tab</kbd> to move focus.

We should probably have a little think about this and maybe redesign the keyboard interaction a little bit. Do you prefer copying with <kbd>Ctrl</kbd>+<kbd>C</kbd> over <kbd>Enter</kbd>, or is the issue rather that the hints in the menus are misleading?

**Comment by alagopus** [comment]
First, yes I think I prefer `Ctrl+C` to `Enter`, but I may get used to `Enter` after a while. But why doesn't the entry get focus when selected by mouse or cursor keys? Also, I think it would be fair to change the menu hint to `Enter`, if that's the only key binding now...

**Comment by alagopus** [comment]
There is even more gone wrong with the entry copy. Previously, the selection was also set along with the cutbuffer.  This distinction is a bit X11 specific but has great bearing on useability. The selection is more ephemeral and can be pasted by `Mouse-Middle` button.

Essentially, in most terminals there is no quick access to clipboard paste because `Ctrl-C` is terminal interrupt instead. The recent regression breaks my workflow and I'm investigating ways to roll back or switch to another device.

**Comment by rmenessec** [comment]
Confirmed this is a problem. I seem to recall we had an identical or very similar bug open for this behavior, and it was previously fixed months ago.

The shortcut listed in the menu is Ctrl+C; therefore the shortcut should be Ctrl+C, and it should work at all times unless the UI/UX clearly suggests that there should be an exception.

Also, when setting focus with the mouse, or attempting to, Ctrl+C still does not work, or works very unreliably at best. This is completely contrary to best practice. I've only gotten Ctrl+C to work by right-clicking an entry, selecting "Copy to clipboard," then pressing Ctrl+C later.

**This isn't how other apps work.** The Desktop Authenticator should be following accepted UI conventions in all cases unless there is a very excellent, clearly stated stated reason otherwise, and any exceptions need to be easily user-discoverable in the UI/UX without resorting to documentation or bug reports to figure out why conventions are being broken.

This should be a guiding principle of this and any UI/UX project: follow accepted conventions until you can't. Don't break user expectations without a good reason.

**Comment by emlun** [comment]
Thank you both, I agree with your criticism. These bugs were introduced as part of implementing #187 (focusing the search field by default), which seemed to me like a good idea - but I was apparently mistaken in judging the breakage as minor. I'll need to discuss this a bit with my colleagues when we're back from vacation a week from now, but right now I deem it likely I'll revert the changes that broke this. I'm sorry, I'll be more careful in the future about changing the UX.

**Comment by dagheyman** [comment]
I've made an attempt to fix this in PR #227 .

**Comment by dagheyman** [comment]
Fixed on master, will be in next release.
