### ISSUE TITLE
Documenting build on a Debian-based system

### ISSUE THREAD

**Issue by replaid** [Yubico/yubioath-desktop#223]
Linux user experience report.

Experience: I run a Debian-based distro. I got a GPG error when adding the Ubuntu PPA repo, so backed out of that approach since I wasn't sure it was the right one for a non-Ubuntu Debian-based distro. 

Feedback: if non-Ubuntu distros can use the Ubuntu PPA repo, please say so. (And let me know if this is the case so I can provide the error message I get if needed.)

Experience: So I turned to the build instructions to build 4.3.0. The needed dependencies are listed in prose, which provides the needed information to solve the problem, but I had to do numerous web searches etc. to figure out what specific packages to install.

Unfortunately I don't have my shell history, but I believe this is the list of packages I needed:

* `qt5-make`
* `qt5-default`
* `qtdeclarative5-dev`
* `qml-module-qtquick-controls`
* `qml-module-qtquick-dialogs`
* the line `deb http://deb.debian.org/debian experimental main` in `/etc/apt/sources.list`
* `qml-module-io-thp-pyotherside`

Feedback: please mention these specific dependencies in your build instructions.

Experience: I had to scrounge around the Internet to figure out how to get an application icon.

Feedback: Please mention in the build instructions that I can copy the icon to `~/.icons/` (or other location you recommend), the `.desktop` file to `~/.local/share/applications/`, and a reminder that `yubioath-desktop` needs to be in my `$PATH` for the icon to appear.

Experience: This was a lot of steps.

Feedback: please provide a Debian package.

And then after all this, it didn't see my YubiKey, even though YubiKey Personalization Tool (which I was able to install through my OS's GUI software install app) does. Filing a separate bug report #224 for that.

**Comment by emlun** [comment]
Thanks a lot for your detailed feedback! The build from source instructions are quite new, so there are certainly some ways they could be improved.

>I got a GPG error when adding the Ubuntu PPA repo

What error? I managed to add the PPA repo with no problems in Debian Jessie, although `apt-get update` then proceeds to not find any packages for the `jessie` distribution (which is reasonable, since none exist).

>if non-Ubuntu distros can use the Ubuntu PPA repo, please say so. (And let me know if this is the case so I can provide the error message I get if needed.)

Most probably can't, unfortunately, since each distro has its own small differences in how things are packaged, but you're welcome to try. It just might work for distros similar enough to Ubuntu. It looks like it's close to compatible with Debian Buster, except the `qml-module-io-thp-pyotherside` package doesn't exist and the `pyotherside` package ships version 1.2 whereas yubioath-desktop requires version 1.4.

>please mention these specific dependencies in your build instructions.

The specific package names will be different for each distro, so it's unfortunately not sustainable for us to keep track of all of them. We provide an Ubuntu package as a reference, but I see now that we could point that out explicitly in the build instructions.

>Please mention in the build instructions that I can copy the icon to ~/.icons/ (or other location you recommend), the .desktop file to ~/.local/share/applications/, and a reminder that yubioath-desktop needs to be in my $PATH for the icon to appear.

These things are all mentioned, at least on a surface level, in the [Packaging][packaging] section of the build instructions. I suppose we could rename that to "Installation", and make it a little clearer where each of the files needs to go.

>please provide a Debian package.

We would like to, but we don't currently have a concrete plan for when it might happen. We would need to host it in our own repository (since there's too much friction in getting it released in the central Debian repos), so we'll need to sort out the infrastructure and processes for that.

[packaging]: https://developers.yubico.com/yubioath-desktop/Building_from_Source.html#_packaging

**Comment by replaid** [comment]
Zooming out a bit...in terms of end-user experience, it's simply this weirdly huge dropoff between the experience for a Mac user (download and done!), Ubuntu user (enter these 2 commands and done!), versus a user of another Linux (go search the Internet for what to install and how to install it, and then find that even those bits of information lacked mention of how to fill key dependencies). 

I'm just a YubiKey customer who happens to have some tech chops, but it's this research project to build your released app that is a core piece of YubiKey's value proposition for me.

Maybe an AppImage or snap might be appropriate?

**Comment by emlun** [comment]
The build docs have now been updated in response to your feedback. Thank you for taking the time to help us improve our evidently lacking build-from-source instructions!

Thanks also for the AppImage suggestion. We'll look into that, but my initial exploration of what it would mean for this project indicates it's probably easier said than done.
