### ISSUE TITLE
yubioath: cannot import name qt_resources

### ISSUE THREAD

**Issue by bricewge** [Yubico/yubioath-desktop#28]
```
$ yubioath                   
Traceback (most recent call last):
  File "/bin/yubioath", line 3, in <module>
    from yubioath.gui import main
  File "/usr/lib/python2.7/site-packages/yubioath/gui/__init__.py", line 27, in <module>
    from . import qt_resources
ImportError: cannot import name qt_resources
```
Commenting out `from . import qt_resources` from `yubioath/gui/__init__.py` fix the issue.

**Comment by dainnilsson** [comment]
Commenting that line out may remove the error, but it also removes all the images from the application (icons for buttons, systray, etc.) so I wouldn't recommend it.

The file you're missing is generated by the packaging scripts, and should be available if you install the application using one of the methods described in the README. May I ask how you installed the application?

**Comment by bricewge** [comment]
Yes there is no icons, I didn't noticed it first.
I had this issue when packaging it for the Archlinux User Repository (AUR), here is the [recipe](that I used).
If I understand it well, I'm missing `yubioath/gui/qt_resources.py` because `python2 setup.py install --root=${pkgdir}` didn't generated for me.

**Comment by dainnilsson** [comment]
That recipe is incorrect, as it does not generate the required files (as you're already noticed). I don't know very much about packaging for Arch, but instead of using the git repository, could it use the actual source release tarball (either from https://developers.yubico.com/yubioath-desktop/Releases/ or from https://pypi.python.org/pypi/yubioath-desktop/)? Note that the tarballs on the Github "Releases" page are auto-generated snapshots of the repository, and not suitable for use. Using a release tarball ensures that all generated files are present, and that the source code is in a good (release worthy) state.

If you insist on building from the git repository directly, you will need to add pyside-tools as a build dependency, and run "python setup.py qt_resources" prior to running "python setup.py install".

**Comment by bricewge** [comment]
This recipe is a git one, this is why it' using the git repo directly. If needed I'll do a stable one.

Thanks, now it's working. Sorry for my noobiness.
