### ISSUE TITLE
Can't install Yubioath on Windows 8.1

### ISSUE THREAD

**Issue by SueHeim** [Yubico/yubioath-desktop#29]
Just tried to install latest Yubioath for Desktop version 2.1.0 (on Windows 8.1) and it's erroring out on me. The first error says "Error opening file for writing" and the file is Crypto.Cipher._AES.pyd. Ignoring that and I get more Crypto*.pyd errors. So I had to abort the install. The previous version installed without any issues. (I uninstalled the previous version but didn't do a reboot.) See attached screen shot. Please let me know if you need more info. Thanks!
![yubicoauthenticator install bug](https://cloud.githubusercontent.com/assets/12145100/8387620/f219b9f6-1c0e-11e5-90c3-06209d76fb17.PNG)

**Comment by dainnilsson** [comment]
It looks like one or more files might be locked by the system. Could the
app still have been running when you uninstalled it? Since it stays in the
tray when you close it it's easy to overlook. If it's still running that
would explain the files being locked. Quitting the program completely and
again trying the installer should work if that's the case.

**Comment by SueHeim** [comment]
Oh. Duh. It let me uninstall an app that was still running? LOL!

Let me try that now! (And why are you answering email at midnight?)

**Comment by SueHeim** [comment]
Reopening actually... make this a low priority, but at some point maybe you could add a check to see if the application is running in the system tray and, if it is, prevent it from being uninstalled? Thanks for your help!

**Comment by dainnilsson** [comment]
Thanks. Closing this as I've opened #30 instead, with a clearer description.
