### ISSUE TITLE
Subset of QR codes not recognized

### ISSUE THREAD

**Issue by Yubi-David** [Yubico/yubioath-desktop#308]
- Yubico Authenticator version: **4.3.4**
- Operating system and version: **Windows 10, ver1803**
- YubiKey model and version: YubiKey 4, YubiKey NEO
- Bug description summary: 
When attempting to scan a QR code for an OATH-TOTP credential generated by 1password (see attached screenshot), the Yubico Authenticator App does not recognize it as a QR code image. Other applications, including the Android version of the Yubico Authenticator recognize and decode the image without issue.

Steps to reproduce
---
1) Open Yubico Authenticator.
2) Display the screenshot on the main monitor.
3) From the Yubico Authenticator, select File > Scan QR code.

Expected result
---
Yubico Authenticator recognizes the QR code, decodes the information included, and auto-populates it in to the correct fields.

Actual results
---
Yubico Authenticator displays an error stating it does not recognize any QR code.

Other info
---
Android version of Yubico Authenticator works. Google Authenticator works as well.

Screenshots of desktop + only QRCode+Secret attached.
![qr_code_cropped](https://user-images.githubusercontent.com/3868709/45104401-a7987f80-b0f7-11e8-98ce-ed247c88d36a.png)

![qr_code](https://user-images.githubusercontent.com/3868709/45104763-6d7bad80-b0f8-11e8-8c66-d0a43ad79faf.png)

**Comment by dagheyman** [comment]
This is the encoded URI:

```
otpauth://totp/1Password:my.1password.com?secret=ATU7T6CF3RFRD4AL&issuer=1Password&skid=Y8X7NB
```
It fails because of the extra `skid` parameter. This is not a defined parameter in the [Key-Uri-Format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format), but I think we could probably just ignore it. This would require a new release of the software, 1Password could also fix it on their side by not including this parameter (I have confirmed that this works).
