### ISSUE TITLE
Export and backup Yubico Authenticator Database?

### ISSUE THREAD

**Issue by AgentOwl** [Yubico/yubioath-desktop#309]
I like it, thx! :-) I have Yubico Authenticator 3.0.1 at KUbuntu 18.04.1 LTS with YubiKey 4.

Can I copy the authenticator database to 2 or more PCs? How to do it?
Backup is always necessary and I use 2 or more PCs.

**Comment by dagheyman** [comment]
Hi, glad you like the project.

The credentials are stored on your YubiKey (there is no database on the PC), so they will work on any desktop or phone with Yubico Authenticator. There is no option to export the secrets from the YubiKey though, so if you need to keep a backup, you will need to program two YubiKeys with the same credential.

Please direct further questions to [Yubico Support](https://support.yubico.com/support/tickets/new), since they have higher bandwidth to answer questions like this.
