### ISSUE TITLE
Show credentials after a touch for already yubikey registered accounts

### ISSUE THREAD

**Issue by alexandre1985** [Yubico/yubioath-desktop#330]
- Yubico Authenticator version: 4.3.4
- Yubikey OATH version: 5.1.2
- Operating system and version: Manjaro Linux Deepin
- YubiKey model and version: Yubikey 5 NFC

I want all my existing website credentials that are on Yubico Authenticator to be activated only if a touch is performed. The credentials code I want it to be displayed only after a touch, that is what I mean.
Right now I only have the latest website that I registered with my yubikey topt authentication with this functionality. I want all the other that I've registered in the past to also only show the code credential only after a touch.
How can I do that?

**Comment by emlun** [comment]
Hi,

The touch flag is stored on creation in the immutable OATH credential on the YubiKey, so I'm afraid you'll have to regenerate those TOTP secrets for which you want to require touch. Even then, because of hardware limitations it's not possible to have them all generated at once with one touch - you'd have to request a specific one at a time and touch the YubiKey for each.

**Comment by alexandre1985** [comment]
Requesting specific one at a time is not a problem @emlun .
Thank you
