### ISSUE TITLE
Seg Fault on Linux

### ISSUE THREAD

**Issue by m0rr1gan** [Yubico/yubioath-desktop#491]
- Yubico Authenticator version: 5.0.1
- Operating system and version: Arch Linux 5.3.11
- YubiKey model and version: YubiKey 5 NFC 5.1.1
- Bug description summary: yubioath-desktop does not register that a yubikey is plugged in and subsequently segfaults when closed

Steps to reproduce
---

1. Start yubioath-desktop
2. it does not register that a yubikey is plugged in
3. closing, it segfaults and generates a core dump

Expected result
---

Start yubioath-desktop, it takes a second to register that a yubikey is plugged in, then displays OATH credentials.

Actual results
---

When I start yubioath-desktop, no yubikeys show up even though they are registered in yubikey-manager-qt and ykman cli. Upon closing yubioath-desktop, a segfault is hit.

Other info
---

coredump: http://ix.io/21PC
runtime output: http://ix.io/21PD

This behavior was confirmed by another Arch user in IRC.

**Comment by gbcox** [comment]
Not seeing this issue on Fedora 31.

Device type: YubiKey 5 NFC
Firmware version: 5.1.2
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP+FIDO+CCID
NFC interface is enabled.
Yubico Authenticator 5.0.1

Previously experienced issue that seemed to be #488, but since upgraded to current master of yubikey-manager git 1f22620 no longer experiencing that issue.

**Comment by linxon** [comment]
>runtime output: http://ix.io/21PD

>"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.init' (Traceback (most recent call last):

you need downgrade yubikey-manager to [2.1.1](https://github.com/Yubico/yubikey-manager/releases/tag/yubikey-manager-2.1.1)

**Comment by Mitch9378** [comment]
I am also experiencing this issue with yubikey-manager 3.1.0-2 on Arch Linux.

@gbcox it seems Fedora 31 is using a slightly older version:

https://apps.fedoraproject.org/packages/yubikey-manager

3.0.0-6

When you saying you are not experiencing this issue on Fedora 31 are you talking about with the Fedora  31 packaged version as well or just with the most recent build from master as you mentioned?

Just want to be sure because it may help narrow down when this was introduced.

**Comment by gbcox** [comment]
Sorry, I ran some tests and the problem is with yubioath-desktop, not yubikey-manager.  The problem occurs with:  yubioath-desktop-5.0.0-2.git121efe3.fc31.x86_64
segfault at 7f094c7cfb60 ip 00007f095dcb41cb sp 00007ffcdeeb3bd0 error 7 in libQt5Quick.so.5.12.5[7f095db7c000+2d0000]

The problem doesn't occur with:  yubioath-desktop-5.0.1-2.gitc58db92.fc31.x86_64

**Comment by disp4287** [comment]
Confirmed.

Yubico Authenticator version: 5.0.1
Operating system and version: Arch Linux 5.3.12
YubiKey model and version: YubiKey 4

Log: https://pastebin.com/pn9ivxRF

Are there any known workarounds for this issue? I'm heavily using my YubiKey for 2FA and I can't access some of my accounts due to this problem.

**Comment by Mitch9378** [comment]
@disp4287 

you can use the AppImage as a workaround:

https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.0.1-linux.AppImage

I confirmed it is working.

**Comment by emlun** [comment]
Confirmed. This seems to be because Python 3.8 broke compatibility with [this line of code](https://github.com/Yubico/yubioath-desktop/commit/2dd9e0186e81e59351761260982f8da4c0a28b15#diff-37015d3190a459fab4798a162c842631R27). We'll see what we can do.

**Comment by emlun** [comment]
Confirmed also that downgrading to Python 3.7 works. So, currently available workarounds are:

- Downgrade Python packages: `python-3.7.4-2` and `python-pyotherside-1.5.8-1` or earlier
- Use the AppImage: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.0.1-linux.AppImage
- Use the [Android](https://play.google.com/store/apps/details?id=com.yubico.yubioath) or [iOS](https://apps.apple.com/us/app/yubico-authenticator/id1476679808) mobile app instead

**Comment by Maryse47** [comment]
Downgrading python on Arch Linux will break all other python packages so it shouldn't count as a workaround.
