### ISSUE TITLE
Enhancement: limit number of codes generated per session.

### ISSUE THREAD

**Issue by brendanhoar** [Yubico/yubioath-desktop#58]
[This covers tightening up code-generation security a bit in the desktop authenticator w/o requiring changes to the applet/hardware.]

Preamble (cross-posted from forum):
I understand the threat model that OTPs are meant to mitigate: remote reuse of login credentials from a machine not under the control of the rightful account holder. Man-in-the-middle and/or Man-in-the-browser threats/attacks are generally out-of-scope for OTPs, but may become in-scope for certain OTP-enabled applications that require additional safeguards.

That being said, because a) the yubikeys (esp. nano/-n models) are often left in the USB port for long periods of time *and* b) because the desktop version of Yubico Authenticator will continuously generate TOTP codes for all accounts *and* c) because desktop systems can get compromised pretty easily...sum all three items together results in an opinion that leaving the code generation going on for hours/days by default is not the best default choice.

Having to remember to explicitly quit the authenticator (esp. because alt-f4 puts it in the windows system tray, continuing to generate codes) or pull out the key (which will interfere with PIV or PGP operations) seems to require a bit too much active mitigation on the part of the end user. It's not "default safe", it's "default convenient".

Enhancement suggestion (rewritten and expanded based on forum post):
1) A local-software mitigation would be:

* The most secure option: hard-coding a small number of consecutive code generations before the password is discarded and re-prompted for (e.g. 3 or 5), but perhaps current users will balk at this.
* A somewhat less secure option but more secure than the "continuous by default" behavior: adding a local setting for the number of consecutive code generations. Allow 0 for continuous, perhaps, or don't because it's really not a good idea. Limit configuration to single or double digits (e.g.0/1-9 or 0/1-99), defaulting to something reasonable such as 3 or 5. 
* The decision on the above is to find the right balance between security and UX.

2) Also note: hardcoding a single-code-before-re-locking is not recommended with the current model due to 30-second-window timing issues, so "1" being hardcoded would probably not work well. Though, perhaps if "1" is chosen (for either option above), the code could delay the single request until the beginning of the use window?

3) And lastly, if there's a countdown of number of tries, it could be added to the code-display dialog box.

Thanks for the consideration.
Brendan

**Comment by dainnilsson** [comment]
So I've been thinking about this a bit, and I'd like to get your take on an idea:

What about instead of making it time (or number of calculations) based, taking a slightly different approach:

Currently when a password is entered, and the user does not check the "Remember password" checkbox, the key is kept in memory until the process ends. Instead, what if the password was cleared when the window is minimized (possibly with a setting to keep the old behavior, but make this new behavior the default)? The way I see it this should mitigate the "unintended unlocked key" scenario, as having the application visible on screen with fresh codes is a clear indicator that the device is not locked. A user could potentially still forget about the window by covering it with another window, but I think that might be a bit of a stretch.

**Comment by dainnilsson** [comment]
The approach described in my previous comment has been implemented (clear password on hide) so I'm now closing this issue. If this fix doesn't do enough, please re-open the issue (or open a new one).
