### ISSUE TITLE
Timeout lock, physical tap on generate and couple of more questions

### ISSUE THREAD

**Issue by dave7280** [Yubico/yubioath-desktop#597]
Hi,

I have couple of questions.

1. Does the windows port of this app, has option to automatically lock the application and require password after X minutes/hours?

2. Are the 2FA codes codes as easily viewable windows text elements or is it printed as the "image"? I found this concept in "WinAuth" application which states:

_"Finally, all codes are **drawn** directly onto the screen to prevent any malware from “windows spying”_

So i'd like to know how it works with yubico authenticator and whenever such features has been implemented, as this sounds good security-wise.

3. Have you considered integrating option to require touch before 2FA code is generated (generate on demand)?

I have yubikey plugged in most of the time and i'm afraid of malicious apps that can read the codes from memory, while i have the application on. Touch and lockout would make these less likely.

4. Any way to increase font size? With DPI at 125% scaling in WQHD (2560x1440) monitor the fonts look quite small.

**Comment by dave7280** [comment]
Answering to myself as i had older version and now downloaded v4

1. It has timeout lock feature but i cannot find any option to set the timeout value.
2. Remains unknown
3. There's tap to touch option but ONLY for new entries.

**Comment by dagheyman** [comment]
Hi, I'll try to give some answers.

1. If the YubiKey has a password set, it is required every time it's inserted, unless the "Remember password" option is used, in case it is remembered locally on the computer. No option to set a timeout.
2. No special handling, they are currently just text.
3. Yes, that is supported on the YubiKey 4 and 5 series. The setting is stored on the YubiKey itself, that's why it cant be edited on existing accounts.
4. No in-app setting for font size.

Closing this, if you want to discuss/request anything related to these, please open separate issues. Thanks!
