### ISSUE TITLE
Feature request: Documentation on password saving functionality

### ISSUE THREAD

**Issue by gdonval** [Yubico/yubioath-desktop#729]
- Yubico Authenticator version: 5.0.5
- Operating system and version: Archlinux
- YubiKey model and version: 5 nano
- Bug description summary: 

This is a feature request for documentation.

TOTP password is not remembered in the Flatpak version of the app. 

That much would not be your problem if how password saving was implemented was documented.

See https://github.com/flathub/com.yubico.yubioath/issues/14

**Comment by fdennis** [comment]
If you choose to remember the password you should see this in `~/.ykman/oath.json`

**Comment by gdonval** [comment]
@fdennis Thanks! Is there any documentation about the format of the password on disk? More particularly, is it just an obfuscated password that is saved or something safer (like it actually needs the yubikey to be transformed back into a usable form).

**Comment by fdennis** [comment]
@gdonval We derive a `derived_key` from the password and a salt (stored on the YubiKey). This `derived_key` is stored in the file. In order to unlock the YubiKey you need the file and the YubiKey.
Here is the code to derive the key https://github.com/Yubico/yubikey-manager/blob/main/yubikit/oath.py#L272
You can read more about this here https://developers.yubico.com/OATH/YKOATH_Protocol.html under SET_CODE and VALIDATE.

**Comment by gdonval** [comment]
Ah brillant thanks! This answers everything.
