### ISSUE TITLE
Wrong Keys?

### ISSUE THREAD

**Issue by vo5tr0** [Yubico/yubioath-desktop#77]
Hey,
I have some trouble with the windows client. The generated keys are not working. Do you have any idea how I can fix that? There is no problem with the android authenticator via nfc...

Best regards
Julian

**Comment by dainnilsson** [comment]
If I'm understanding you correctly, the Windows client is generating codes, but these codes are not being accepted by the remote services? If so it sounds to me like the issue is clock synchronization. The TOTP protocol relies on the time of the client and server being synchronized, so if the clock is off by several seconds or minutes, the codes generated might already be expired (or not yet valid). Clock synchronization is typically handled by the operating system automatically.

**Comment by vo5tr0** [comment]
Thank you for your answer! The Problem was caused by my USB Hub...
Am 21.03.2016 12:42 nachm. schrieb "Dain Nilsson" <notifications@github.com
