### ISSUE TITLE
Authenticator deleted (or is hiding) all my accounts after verifying input monitoring on Mac

### ISSUE THREAD

**Issue by edelstone** [Yubico/yubioath-desktop#770]
- Yubico Authenticator version: 5.1.0
- Operating system and version: MacOS 12.1
- YubiKey model and version: Nano 5C
- Bug description summary: When trying to open the authenticator to get a code for one of my 2FA accounts, I was prompted by MacOS to give input monitoring access to the authenticator app in System Preferences > Security & Privacy > Input Monitoring. Simultaneously, the Authenticator had an error at the bottom of the UI saying "Failed to connect to Yubikey". I had never seen the MacOS prompt until now, after two years of continuous use of my Nano 5C and the Authenticator app version downloaded from the Mac App Store. I wasn't really sure why the app needed keyboard access but it didn't seem like a huge deal to me so I granted access. When I quit and reopened the Authenticator, the error at the bottom goes away, but now the UI says I have no accounts set up. I have about 15 accounts set up in reality, and am absolutely certain of this. So, um, what the hell is going on? I have a backup Yubikey with all the same accounts on it but I'm legitimately scared to connect it to your authenticator. What should I do here?

Steps to reproduce
---
1. Open the authenticator app with Yubikey in USB slot
2. Grant access to security settings for input monitoring when prompted (not sure why this prompt happened right now all of a sudden, though)
3. Quit and reopen the authenticator app

Expected result
---
Normal functionality

Actual results
---
All of my accounts are gone, according to the Yubikey app.

Other info
---

This is terrifying.

<img width="510" alt="Screen Shot 2022-01-14 at 5 06 55 AM" src="https://user-images.githubusercontent.com/8269046/149507135-5c6581ed-e44a-4163-bfa0-0b2dda785397.png">
<img width="780" alt="Screen Shot 2022-01-14 at 5 07 02 AM" src="https://user-images.githubusercontent.com/8269046/149507138-e6f33e4a-8db5-4cc8-8e15-894523395768.png">
<img width="780" alt="Screen Shot 2022-01-14 at 5 07 09 AM" src="https://user-images.githubusercontent.com/8269046/149507141-981792ca-d365-4a6d-94a5-c5353ff35a6c.png">
<img width="510" alt="Screen Shot 2022-01-14 at 5 07 20 AM" src="https://user-images.githubusercontent.com/8269046/149507142-88a02874-0d90-47f4-8e7d-3aa585d989ce.png">

**Comment by fdennis** [comment]
Hi.
Have you tried rebooting your computer and seeing if the problem is still there?
Furthermore, could you run the app through the terminal with the debug flag, like this` ./yubico-authenticator --log-level DEBUG` , and send that to us? You should be able to find the app under `/Applications/Yubico Authenticator.app/Contents/MacOS`
There is also a CLI available called ykman. You can install this to check on your accounts. Install ykman through brew with `brew install ykman` and then run` ykman oath accounts list `to see all accounts on the YubiKey. It would also be helpful if you could run `ykman --diagnose` and provide us with the output it gives.

**Comment by edelstone** [comment]
Sounds good to me. Thanks much for the fix.
