### ISSUE TITLE
Old libccid in Debian 8 Jessie does not recognize Yubikey 4

### ISSUE THREAD

**Issue by rcsanchez97** [Yubico/yubioath-desktop#96]
I recently purchased a new YubiKey 4 nano.  I use Linux as my primary OS and I was able to easily and quickly associate the YubiKey with my Gmail account using Chromium on Debian 8 Jessie.  However, when I tried to associate it as a virtual MFA device for my AWS account, I was not able to get it working.  I updated the Yubico Desktop Authenticator app to the latest version (3.0.1) and also the libraries libykpers-1-1 (1.17.3) and libyubikey0 (1.16.0).  However, I was still not able to associate the device to AWS.  I switched to Windows 8.1 and downloaded the Yubico Desktop Authenticator app for Windows and was able to immediately associate the device with my AWS account.

The UI in Linux shows a place for slot 1 and slot 2, while the UI in Windows does not show that.  In Linux when I select File -> Add the dialog does not let me set a credential name, but rather wants me to select either slot 1 or slot 2.  Additionally, the 64 character base32 key from AWS causes an exception at line 145 of core/legacy_otp.py.  Also, on Linux the File -> Set/change password option is always greyed out.  On Windows, the File -> Add dialog lets me set a credential name, accepts the 64 character base32 key from AWS and does not force me to choose one of two slots.

Even after loading the key and configuring the TOTP for AWS on Windows, opening the authenticator app on Linux shows no evidence of the TOTP I just configured.  I also tried the yubikey-totp command-line tool on Linux, but it always terminates with the message "ERROR: Timed out waiting for YubiKey to set status 0x40".

I would like to help resolve this and make the YubiKey experience better on Linux for myself and others.  Please let me know what I can do to help.

**Comment by dainnilsson** [comment]
This app supports the newer OATH functionality available in YubiKey NEO and YubiKey 4, which is smartcard-based and allows for a larger number (30+) of credentials (as well as additional features such as names, etc.), but it also supports the older slot-based OATH feature available in older YubiKeys as a fallback (which is limited to 2 unnamed credentials).

The behavior you are describing indicates that on Windows you're getting the correct "new" feature, but on Linux it is falling back to the "older" capabilities. This in turn indicates that the app isn't able to access the newer smartcard based OATH capability of your YubiKey, which may be due to an outdated libccid. It's recommended to update libccid to the latest version, as that tends to be more stable overall, but it's possible to use an older version as well if you manually patch the list of supported smartcard readers that comes with it. We provide a script that helps you do just that here: https://github.com/Yubico/yubioath-desktop/blob/master/resources/linux-patch-ccid

**Comment by rcsanchez97** [comment]
It looks like libccid was the piece I overlooked.  The version in Debian 8 is approximately two years old, which would explain why it didn't recognize the Yubikey 4 properly.  I added the new entries then when I launched the authenticator app, everything worked as expected.  I was able to remove existing credentials, add new credentials up to the 64 character limit for the base32 secret key, etc.  I have retitled this issue to make it easier for others who find it to understand the real nature of the problem.  I am also closing it as this clearly not an issue with the app, but with the libraries included in my system.  Thanks again for the quick and helpful reply.
